# Generated by Django 4.1.13 on 2025-03-08 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='disconnected', max_length=50)),
                ('last_heartbeat', models.DateTimeField(null=True)),
                ('meter_value', models.FloatField(default=0.0)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chargers',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_tag', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField(null=True)),
                ('meter_start', models.IntegerField()),
                ('meter_stop', models.IntegerField(null=True)),
                ('reason', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='chargers.charger')),
            ],
        ),
    ]
